defaults:
  - agent: mdp
  - override hydra/launcher: submitit_local

# task settings
task: walker_walk
algorithm: icm
discount: 0.99

# train settings
num_grad_steps: 400010 # NUMBER  OF TRAINING STEPS
log_every_steps: 1000
# eval
eval_every_steps: 10000
num_eval_episodes: 10
# snapshot
snapshots: [0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000, 550000, 600000, 650000, 700000, 750000, 800000]
snapshot_dir: snapshots # If not absolute, this goes in cwd
# resume
resume: true
resume_dir: ??? # If resume is true, this has to be specified
resume_step: 400000

## Stuff
replay_buffer_size: 100000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}
# misc
seed: 1
device: cuda
save_video: false
use_tb: false
use_wandb: false
project: finetune_ppo
notes: "finetune_ppo"
exp_name: output

# This is the working directory for the script
hydra:
  run:
    dir: "/home/bibarel/workspace/ppo_models/"
