_wandb:
    value:
        cli_version: 0.21.4
        e:
            htjdmrgu4xacw4t0ncux4413co5jq6a3:
                email: bibarelusedfly@gmail.com
                executable: /home/dcc/miniconda3/envs/maskdp/bin/python
                git:
                    commit: e1f2bcf40d7a02176c0d57402235538662aba511
                    remote: https://github.com/BibarelUsedFly/maskdp-taskgeneral.git
                host: DCC-B40-1
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.17
                program: pretest.py
                python: CPython 3.8.20
                root: /home/dcc/maskdp-taskgeneral/models
                startedAt: "2025-09-21T07:35:03.420379Z"
                writerId: htjdmrgu4xacw4t0ncux4413co5jq6a3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 13
                - 16
            "4": 3.8.20
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
agent:
    value:
        _target_: agent.mdp.MaskedDPAgent
        action_shape:
            - 6
        batch_size: 16
        device: cpu
        lr: 0.0001
        mask_ratio:
            - 0.15
            - 0.35
            - 0.55
            - 0.75
            - 0.95
        name: mdp
        obs_shape:
            - 24
        transformer_cfg:
            attn_pdrop: 0
            embd_pdrop: 0
            loss: total
            n_dec_layer: 1
            n_embd: 128
            n_enc_layer: 1
            n_head: 2
            norm: l2
            pe: fixed
            resid_pdrop: 0
            traj_length: 128
        use_tb: false
batch_size:
    value: 16
device:
    value: cpu
discount:
    value: 0.99
eval_every_steps:
    value: 10000
exp_name:
    value: output
log_every_steps:
    value: 1000
notes:
    value: pretrain
num_eval_episodes:
    value: 10
num_grad_steps:
    value: 10
project:
    value: mdp
replay_buffer_dir:
    value: ../maskdp_data/maskdp_train
replay_buffer_num_workers:
    value: 16
replay_buffer_size:
    value: 100000000
resume:
    value: false
resume_dir:
    value: none
resume_step:
    value: 0
save_video:
    value: true
seed:
    value: 1
snapshot_dir:
    value: ./snapshots
snapshots:
    value:
        - 0
        - 100000
        - 200000
        - 300000
        - 350000
        - 400000
        - 450000
        - 500000
        - 550000
        - 600000
task:
    value: walker_walk
use_tb:
    value: false
use_wandb:
    value: true
